# Generated by Django 3.1.1 on 2024-02-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='excel_path',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='drive_path',
            field=models.CharField(max_length=1000),
        ),
    ]
